### ISSUE TITLE
Choose page: after entering wished name and press enter it creates a random name

### ISSUE THREAD

**Issue by firepol** [angelol/eos_account_creator#1]
Hi, I encountered this unexpected behavior in this page: https://eos-account-creator.com/choose/

**Steps to reproduce:**

- enter a wished account name, e.g. blablablabla
- press ENTER
- your wished name disappears and instead you get a random one

**Expected behavior:**

"ENTER" should activate the "continue" button, not the "I'm feeling lucky" one.

**Comment by angelol** [comment]
Thank you for reporting, it is fixed now
